<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Modules\Core\Support\PermissionCatalog;

return new class extends Migration
{
    /**
     * Snapshot of the granular permissions at the time authorization moved to route middleware.
     */
    protected const PERMISSIONS = [
        'core.exchange-rates.create' => ['name' => 'Create Exchange Rates', 'group' => 'Administration'],
        'core.exchange-rates.delete' => ['name' => 'Delete Exchange Rates', 'group' => 'Administration'],
        'core.exchange-rates.update' => ['name' => 'Edit Exchange Rates', 'group' => 'Administration'],
        'core.exchange-rates.view' => ['name' => 'View Exchange Rates', 'group' => 'Administration'],
        'core.fiscal-years.create' => ['name' => 'Create Fiscal Years', 'group' => 'Administration'],
        'core.periods.close' => ['name' => 'Close Periods', 'group' => 'Administration'],
        'core.periods.lock' => ['name' => 'Lock Periods', 'group' => 'Administration'],
        'core.periods.reopen' => ['name' => 'Reopen Periods', 'group' => 'Administration'],
        'core.periods.view' => ['name' => 'View Periods', 'group' => 'Administration'],
        'finance.bank-accounts.create' => ['name' => 'Create Bank Accounts', 'group' => 'Finance'],
        'finance.bank-accounts.delete' => ['name' => 'Delete Bank Accounts', 'group' => 'Finance'],
        'finance.bank-accounts.update' => ['name' => 'Edit Bank Accounts', 'group' => 'Finance'],
        'finance.bank-accounts.view' => ['name' => 'View Bank Accounts', 'group' => 'Finance'],
        'finance.bank-reconciliation.create' => ['name' => 'Create Bank Reconciliation', 'group' => 'Finance'],
        'finance.bank-reconciliation.view' => ['name' => 'View Bank Reconciliation', 'group' => 'Finance'],
        'finance.bank-transactions.create' => ['name' => 'Create Bank Transactions', 'group' => 'Finance'],
        'finance.bank-transactions.view' => ['name' => 'View Bank Transactions', 'group' => 'Finance'],
        'finance.budgets.approve' => ['name' => 'Approve Budgets', 'group' => 'Finance'],
        'finance.budgets.reject' => ['name' => 'Reject Budgets', 'group' => 'Finance'],
        'finance.budgets.submit' => ['name' => 'Submit Budgets', 'group' => 'Finance'],
        'finance.cash-accounts.create' => ['name' => 'Create Cash Accounts', 'group' => 'Finance'],
        'finance.cash-accounts.delete' => ['name' => 'Delete Cash Accounts', 'group' => 'Finance'],
        'finance.cash-accounts.update' => ['name' => 'Edit Cash Accounts', 'group' => 'Finance'],
        'finance.cash-accounts.view' => ['name' => 'View Cash Accounts', 'group' => 'Finance'],
        'finance.customer-invoices.approve' => ['name' => 'Approve Customer Invoices', 'group' => 'Finance'],
        'finance.customer-invoices.cancel' => ['name' => 'Cancel Customer Invoices', 'group' => 'Finance'],
        'finance.customer-invoices.create' => ['name' => 'Create Customer Invoices', 'group' => 'Finance'],
        'finance.customer-invoices.delete' => ['name' => 'Delete Customer Invoices', 'group' => 'Finance'],
        'finance.customer-invoices.post' => ['name' => 'Post Customer Invoices', 'group' => 'Finance'],
        'finance.customer-invoices.reject' => ['name' => 'Reject Customer Invoices', 'group' => 'Finance'],
        'finance.customer-invoices.submit' => ['name' => 'Submit Customer Invoices', 'group' => 'Finance'],
        'finance.customer-invoices.update' => ['name' => 'Edit Customer Invoices', 'group' => 'Finance'],
        'finance.customer-invoices.view' => ['name' => 'View Customer Invoices', 'group' => 'Finance'],
        'finance.dashboard.view' => ['name' => 'View Dashboard', 'group' => 'Finance'],
        'finance.journals.cancel' => ['name' => 'Cancel Journals', 'group' => 'Finance'],
        'finance.journals.reject' => ['name' => 'Reject Journals', 'group' => 'Finance'],
        'finance.journals.reverse' => ['name' => 'Reverse Journals', 'group' => 'Finance'],
        'finance.payments.reject' => ['name' => 'Reject Payments', 'group' => 'Finance'],
        'finance.receipts.reject' => ['name' => 'Reject Receipts', 'group' => 'Finance'],
        'finance.recurring-journals.create' => ['name' => 'Create Recurring Journals', 'group' => 'Finance'],
        'finance.recurring-journals.delete' => ['name' => 'Delete Recurring Journals', 'group' => 'Finance'],
        'finance.recurring-journals.update' => ['name' => 'Edit Recurring Journals', 'group' => 'Finance'],
        'finance.recurring-journals.view' => ['name' => 'View Recurring Journals', 'group' => 'Finance'],
        'finance.supplier-debit-notes.approve' => ['name' => 'Approve Supplier Debit Notes', 'group' => 'Finance'],
        'finance.supplier-debit-notes.submit' => ['name' => 'Submit Supplier Debit Notes', 'group' => 'Finance'],
        'finance.supplier-invoices.approve' => ['name' => 'Approve Supplier Invoices', 'group' => 'Finance'],
        'finance.supplier-invoices.cancel' => ['name' => 'Cancel Supplier Invoices', 'group' => 'Finance'],
        'finance.supplier-invoices.create' => ['name' => 'Create Supplier Invoices', 'group' => 'Finance'],
        'finance.supplier-invoices.delete' => ['name' => 'Delete Supplier Invoices', 'group' => 'Finance'],
        'finance.supplier-invoices.post' => ['name' => 'Post Supplier Invoices', 'group' => 'Finance'],
        'finance.supplier-invoices.reject' => ['name' => 'Reject Supplier Invoices', 'group' => 'Finance'],
        'finance.supplier-invoices.submit' => ['name' => 'Submit Supplier Invoices', 'group' => 'Finance'],
        'finance.supplier-invoices.update' => ['name' => 'Edit Supplier Invoices', 'group' => 'Finance'],
        'finance.supplier-invoices.view' => ['name' => 'View Supplier Invoices', 'group' => 'Finance'],
    ];

    protected const LEGACY_EQUIVALENTS = [
        'core.exchange-rates.create' => ['finance.accounts.update'],
        'core.exchange-rates.delete' => ['finance.accounts.update'],
        'core.exchange-rates.update' => ['finance.accounts.update'],
        'core.exchange-rates.view' => ['finance.accounts.view'],
        'core.fiscal-years.create' => ['finance.accounts.update'],
        'core.periods.close' => ['finance.accounts.update'],
        'core.periods.lock' => ['finance.accounts.update'],
        'core.periods.reopen' => ['finance.accounts.update'],
        'core.periods.view' => ['finance.reports.view'],
        'finance.bank-accounts.create' => ['finance.accounts.create'],
        'finance.bank-accounts.delete' => ['finance.accounts.delete'],
        'finance.bank-accounts.update' => ['finance.accounts.update'],
        'finance.bank-accounts.view' => ['finance.accounts.view'],
        'finance.bank-reconciliation.create' => ['finance.accounts.create'],
        'finance.bank-reconciliation.view' => ['finance.accounts.view'],
        'finance.bank-transactions.create' => ['finance.accounts.create'],
        'finance.bank-transactions.view' => ['finance.accounts.view'],
        'finance.budgets.approve' => ['finance.budgets.update'],
        'finance.budgets.reject' => ['finance.budgets.update'],
        'finance.budgets.submit' => ['finance.budgets.update'],
        'finance.cash-accounts.create' => ['finance.accounts.create'],
        'finance.cash-accounts.delete' => ['finance.accounts.delete'],
        'finance.cash-accounts.update' => ['finance.accounts.update'],
        'finance.cash-accounts.view' => ['finance.accounts.view'],
        'finance.customer-invoices.approve' => ['finance.customers.approve'],
        'finance.customer-invoices.cancel' => ['finance.customers.cancel'],
        'finance.customer-invoices.create' => ['finance.customers.create'],
        'finance.customer-invoices.delete' => ['finance.customers.delete'],
        'finance.customer-invoices.post' => ['finance.customers.post'],
        'finance.customer-invoices.reject' => ['finance.customers.approve'],
        'finance.customer-invoices.submit' => ['finance.customers.submit'],
        'finance.customer-invoices.update' => ['finance.customers.update'],
        'finance.customer-invoices.view' => ['finance.customers.view'],
        'finance.dashboard.view' => ['dashboard.view'],
        'finance.journals.cancel' => ['finance.journals.delete'],
        'finance.journals.reject' => ['finance.journals.approve'],
        'finance.journals.reverse' => ['finance.journals.post'],
        'finance.ledger.view' => ['finance.journals.view', 'finance.reports.view'],
        'finance.payments.create' => ['finance.suppliers.create'],
        'finance.payments.reject' => ['finance.payments.approve'],
        'finance.payments.view' => ['finance.suppliers.view'],
        'finance.receipts.create' => ['finance.customers.create'],
        'finance.receipts.reject' => ['finance.receipts.approve'],
        'finance.receipts.view' => ['finance.customers.view'],
        'finance.recurring-journals.create' => ['finance.journals.create'],
        'finance.recurring-journals.delete' => ['finance.journals.delete'],
        'finance.recurring-journals.update' => ['finance.journals.update'],
        'finance.recurring-journals.view' => ['finance.journals.view'],
        'finance.reports.export' => ['finance.reports.view'],
        'finance.supplier-credit-notes.approve' => ['finance.suppliers.approve'],
        'finance.supplier-credit-notes.cancel' => ['finance.suppliers.cancel'],
        'finance.supplier-credit-notes.create' => ['finance.suppliers.create'],
        'finance.supplier-credit-notes.delete' => ['finance.suppliers.delete'],
        'finance.supplier-credit-notes.post' => ['finance.suppliers.post'],
        'finance.supplier-credit-notes.submit' => ['finance.suppliers.approve'],
        'finance.supplier-credit-notes.update' => ['finance.suppliers.update'],
        'finance.supplier-credit-notes.view' => ['finance.suppliers.view'],
        'finance.supplier-debit-notes.approve' => ['finance.suppliers.approve'],
        'finance.supplier-debit-notes.cancel' => ['finance.suppliers.cancel'],
        'finance.supplier-debit-notes.create' => ['finance.suppliers.create'],
        'finance.supplier-debit-notes.delete' => ['finance.suppliers.delete'],
        'finance.supplier-debit-notes.post' => ['finance.suppliers.post'],
        'finance.supplier-debit-notes.submit' => ['finance.suppliers.approve'],
        'finance.supplier-debit-notes.update' => ['finance.suppliers.update'],
        'finance.supplier-debit-notes.view' => ['finance.suppliers.view'],
        'finance.supplier-invoices.approve' => ['finance.suppliers.approve'],
        'finance.supplier-invoices.cancel' => ['finance.suppliers.cancel'],
        'finance.supplier-invoices.create' => ['finance.suppliers.create'],
        'finance.supplier-invoices.delete' => ['finance.suppliers.delete'],
        'finance.supplier-invoices.post' => ['finance.suppliers.post'],
        'finance.supplier-invoices.reject' => ['finance.suppliers.approve'],
        'finance.supplier-invoices.submit' => ['finance.suppliers.submit'],
        'finance.supplier-invoices.update' => ['finance.suppliers.update'],
        'finance.supplier-invoices.view' => ['finance.suppliers.view'],
    ];

    public function up(): void
    {
        PermissionCatalog::install(self::PERMISSIONS, self::LEGACY_EQUIVALENTS);
    }

    public function down(): void
    {
        DB::table('permissions')->whereIn('slug', array_keys(self::PERMISSIONS))->delete();
    }
};
